[workspace]

members = ["crates/*"]

[package]
name = "leafui"
version = "0.1.0"
edition = "2021"

[dependencies]
leaf_nodes = { path = "crates/leaf_nodes" }
leaf_render = { path = "crates/leaf_render" }